create table PARAMS (id bigint generated by default as identity, CODE_P varchar(255), valeur varchar(255), primary key (id));
create table PERS (id bigint generated by default as identity, code varchar(255), name varchar(255), primary key (id));

