create table SimpleEntity (id integer generated by default as identity, 
LLLV varchar(6), SLLV varchar(25), 
NNV integer, 
NUV integer unique, UV integer, 
primary key (id));

insert into SimpleEntity (id,LLLV,SLLV,NNV,NUV,UV) values (1000,'one','two',1,2,3);