--create table GROUPE (id integer generated by default as identity, NAME varchar(25), primary key (id));
--create table ELEMENT (id integer generated by default as identity, NAME varchar(25), GROUPE_FK integer, primary key (id));

insert into GROUPE (ID,NAME) values (1000,'Group1');
insert into GROUPE (ID,NAME) values (1001,'Group2');

insert into ELEMENT (ID,NAME,GROUPE_FK) values (2000,'Element1',1000);
insert into ELEMENT (ID,NAME,GROUPE_FK) values (2001,'Element2',1000);
insert into ELEMENT (ID,NAME,GROUPE_FK) values (2002,'Element3',1000);
insert into ELEMENT (ID,NAME,GROUPE_FK) values (2003,'Element4',1001);
insert into ELEMENT (ID,NAME,GROUPE_FK) values (2004,'Element5',1001);
